name: module
description: https://github.com/champtitles/action-terraform-module
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: echo $AWS_DEFAULT_REGION
      shell: bash
    - run: echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||'
      shell: bash
