name: module
description: https://github.com/champtitles/action-terraform-module
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # global defaults for terraform automation
        export KUBE_CONFIG_PATH=${KUBE_CONFIG_PATH:-~/.kube/config}
        export TF_INPUT=${TF_INPUT:-false}
        export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
        export TF_VAR_branch=$(git branch --show-current)
        export TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')

        # module test code is located in a specific directory
        cd ${TEST_DIRECTORY:-test}

        # load terraform files stored in this action
        cp ${GITHUB_ACTION_PATH}/*.tf .

        # enable cloning of private modules
        if [ -n "${SSH_PRIVATE_KEY}" ]; then
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
        fi

        # target EKS cluster
        aws eks update-kubeconfig --name ${EKS_CLUSTER}

        # execute terraform commands
        terraform init -backend-config key=${TF_VAR_git}/${TF_VAR_branch} -backend-config bucket=${TF_STATE_BUCKET}
        terraform apply -auto-approve
        terraform plan -detailed-exitcode
        terraform destroy -auto-approve
        terraform plan -detailed-exitcode -destroy
        cd .. && terraform fmt -recursive -check
