name: terraform-module
description: https://github.com/champtitles/action-terraform-module
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
      with:
        go-version: 1.16
        
    - name: Download Go depedencies
      run: |
        # module test code is located in a specific directory
        cd ${TEST_DIRECTORY:-test/src}
        go mod download

    - name: Execute Terratest
      shell: bash
      run: |
        # global defaults for terraform automation
        export TF_INPUT=${TF_INPUT:-false}
        export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
        export TF_VAR_branch=$(git branch --show-current)
        export TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')

        # module test code is located in a specific directory
        cd ${TEST_DIRECTORY:-test/src}

        # enable cloning of private modules
        if [ -n "${SSH_PRIVATE_KEY}" ]; then
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
        fi

        # execute terratest
        go test -v -timeout 60m
