name: terraform-module
description: https://github.com/champtitles/action-terraform-module
runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec
      with:
        terraform_version: 0.15.5

    - name: Set up Go
      uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
      with:
        go-version: 1.16
 
    - name: Execute Terratest
      shell: sh
      run: |
        # global defaults for terraform automation
        export TF_INPUT=${TF_INPUT:-false}
        export TF_IN_AUTOMATION=${TF_IN_AUTOMATION:-true}
        export TF_VAR_branch=$(git branch --show-current)
        export TF_VAR_git=$(echo ${GITHUB_REPOSITORY} | sed -e 's|.*/||')

        # module test code is located in a specific directory
        cd ${TEST_DIRECTORY:-test/src}

        # enable cloning of private modules
        if [ -n "${SSH_PRIVATE_KEY}" ]; then
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
        fi
        
        # download dependencies
        go mod download

        # execute terratest
        go test -v -timeout 60m
