name: terraform-module
description: https://github.com/champtitles/action-terraform-module
runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 0.15.5

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
 
    - name: Execute Terratest
      shell: bash
      run: |
        # module test code is located in a specific directory
        cd test/src

        # enable cloning of private modules
        if [ -n "${SSH_PRIVATE_KEY}" ]; then
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
        fi
        
        # download dependencies
        # go mod download
        go get -v -t -d

        # execute terratest
        go test -v -timeout 90m
